env = Environment(CCFLAGS='-std=c++17 -Wall -O3')
env['LIBS'] = ['pugixml']

targets = {}
for i in range(73, 73+1):
    name = 'p%d' % i
    targets[name] = name + '.cc'

for target in targets:
    objs = targets[target]
    env.Program(target, objs)
