env = Environment(CCFLAGS='-std=c++17 -Wall -O3')
env['LIBS'] = ['stdc++fs', 'zip']
env['LIBPATH'] = ['./wbenny-ziplib/Bin/']
env['CPPPATH'] = ['./wbenny-ziplib/Source/ZipLib']

targets = {}
for i in range(79, 79+1):
    name = 'p%d' % i
    targets[name] = name + '.cc'

for target in targets:
    objs = targets[target]
    env.Program(target, objs)
