env = Environment(CCFLAGS='-std=c++17 -Wall -O3')
env['LIBS'] = ['pthread']

targets = {}
for i in range(61, 66+1):
    name = 'p%d' % i
    targets[name] = name + '.cc'

targets['p61_2'] = 'p61_2.cc'

for target in targets:
    objs = targets[target]
    env.Program(target, objs)
