env = Environment(CCFLAGS='-std=c++17 -Wall -O3')
env['CPPPATH'] = ['./asio/include']
env['LIBS'] = ['pthread']

targets = {}
for i in range(95, 96+1):
    name = 'p%d' % i
    targets[name] = name + '.cc'

targets['p96_c'] = 'p96_c.cc'

for target in targets:
    objs = targets[target]
    env.Program(target, objs)
